# Generated by Django 5.0.1 on 2024-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='r_rated',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('R', 'Released'), ('P', 'In Production')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(choices=[('R', 'Released'), ('P', 'In Production'), ('C', 'Canceled')], max_length=1),
        ),
    ]
