# Generated by Django 5.0.1 on 2024-01-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_episode_total_time_alter_movie_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='featured_movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cinema.movie'),
        ),
        migrations.AddField(
            model_name='genre',
            name='featured_tvshows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cinema.tvshow'),
        ),
    ]
