# Generated by Django 5.0.1 on 2024-01-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_remove_genre_featured_movies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='featured_roles',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='featured_comments',
        ),
        migrations.RemoveField(
            model_name='season',
            name='featured_episodes',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='featured_comments',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='featured_seasons',
        ),
    ]
