# Generated by Django 5.0.1 on 2024-01-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_cast_featured_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='total_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
