# Generated by Django 5.0.2 on 2024-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_episode_description_alter_season_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(),
        ),
    ]
