# Generated by Django 5.0.2 on 2024-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_episode_description_alter_season_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='picture_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
