# Generated by Django 5.0.1 on 2024-01-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='list_ptr',
        ),
        migrations.RemoveField(
            model_name='list',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='list',
            name='object_id',
        ),
        migrations.AddField(
            model_name='list',
            name='featured_objects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('F', 'Favorites'), ('W', 'Watchlist'), ('O', 'Other')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.list')),
            ],
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
