# Generated by Django 5.0.1 on 2024-01-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_watchlist_list_ptr_remove_list_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('F', 'Favorites'), ('W', 'Watchlist'), ('O', 'Other')], max_length=1),
        ),
    ]
