# Generated by Django 5.0.1 on 2024-01-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_list_list_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='featured_objects',
        ),
    ]
