# Generated by Django 5.0.1 on 2024-01-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_list_featured_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
